# E/22/423

# Statistical Mechanics of the Quantum Harmonic Oscillator

The energy eigenvalues of a single quantum harmonic oscillator are:

$$
E_j=\hbar\omega\left(j+\frac{1}{2}\right),
\qquad j=0,1,2,\dots
$$

where:
- $\hbar$ is the reduced Planck constant,
- $\omega$ is the angular frequency,
- $k_B$ is the Boltzmann constant,
- $T$ is the temperature.

---

## 1. Partition Function

The canonical partition function is:

$$
Z(T)=\sum_{j=0}^{\infty} e^{-E_j/(k_BT)}
$$

Substituting the energy levels:

$$
Z=\sum_{j=0}^{\infty}
e^{-\frac{\hbar\omega(j+\frac12)}{k_BT}}
$$

Separating the terms:

$$
Z=
e^{-\frac{\hbar\omega}{2k_BT}}
\sum_{j=0}^{\infty}
e^{-\frac{j\hbar\omega}{k_BT}}
$$

Let:

$$
r=e^{-\frac{\hbar\omega}{k_BT}}
$$

Then:

$$
Z=
e^{-\frac{\hbar\omega}{2k_BT}}
\sum_{j=0}^{\infty}r^j
$$

The geometric series is:

$$
\sum_{j=0}^{\infty}r^j=\frac{1}{1-r}
$$

Therefore:

$$
\boxed{
Z=
\frac{
e^{-\frac{\hbar\omega}{2k_BT}}
}
{
1-e^{-\frac{\hbar\omega}{k_BT}}
}
}
$$


# 2. Thermodynamic Potentials

## Helmholtz Free Energy

The Helmholtz free energy is:

$$
F=-k_BT\ln Z
$$

Using the partition function:

$$
\ln Z=
-\frac{\hbar\omega}{2k_BT}
-\ln
(1-e^{-\frac{\hbar\omega}{k_BT}})
$$

Therefore:

$$
F=-k_BT
\left(
-\frac{\hbar\omega}{2k_BT}
-\ln
(1-e^{-\frac{\hbar\omega}{k_BT}})
\right)
$$

Hence:

$$
\boxed{
F=
\frac{\hbar\omega}{2}
+
k_BT
\ln
(1-e^{-\frac{\hbar\omega}{k_BT}})
}
$$


## Internal Energy

The internal energy is:

$$
U=-\frac{\partial\ln Z}{\partial\beta}
$$

where:

$$
\beta=\frac{1}{k_BT}
$$

The partition function becomes:

$$
Z=
\frac{e^{-\beta\hbar\omega/2}}
{1-e^{-\beta\hbar\omega}}
$$

Taking logarithm:

$$
\ln Z=
-\frac{\beta\hbar\omega}{2}
-\ln(1-e^{-\beta\hbar\omega})
$$

Differentiating:

$$
\frac{\partial\ln Z}{\partial\beta}
=
-\frac{\hbar\omega}{2}
-
\frac{\hbar\omega e^{-\beta\hbar\omega}}
{1-e^{-\beta\hbar\omega}}
$$

Therefore:

$$
U=
\frac{\hbar\omega}{2}
+
\frac{\hbar\omega}
{e^{\beta\hbar\omega}-1}
$$

Hence:

$$
\boxed{
U=
\frac{\hbar\omega}{2}
+
\frac{\hbar\omega}
{e^{\frac{\hbar\omega}{k_BT}}-1}
}
$$


or:

$$
\boxed{
U=
\frac{\hbar\omega}{2}
\coth
\left(
\frac{\hbar\omega}{2k_BT}
\right)
}
$$


# 3. Entropy

Using:

$$
S=\frac{U-F}{T}
$$

Substituting:

$$
S=
\frac1T
\left[
\frac{\hbar\omega}{2}
+
\frac{\hbar\omega}
{e^{\frac{\hbar\omega}{k_BT}}-1}
-
\left(
\frac{\hbar\omega}{2}
+
k_BT
\ln
(1-e^{-\frac{\hbar\omega}{k_BT}})
\right)
\right]
$$

The zero-point energy terms cancel:

$$
\boxed{
S=
k_B
\left[
\frac{\frac{\hbar\omega}{k_BT}}
{e^{\frac{\hbar\omega}{k_BT}}-1}
-
\ln
(1-e^{-\frac{\hbar\omega}{k_BT}})
\right]
}
$$


# 4. Heat Capacity

The heat capacity is:

$$
C_V=
\left(
\frac{\partial U}{\partial T}
\right)_V
$$

Using:

$$
U=
\frac{\hbar\omega}{2}
\coth
\left(
\frac{\hbar\omega}{2k_BT}
\right)
$$

Let:

$$
x=
\frac{\hbar\omega}{2k_BT}
$$

Then:

$$
C_V=
k_B
x^2
\frac{1}{\sinh^2(x)}
$$

Therefore:

$$
\boxed{
C_V=
k_B
\left(
\frac{\hbar\omega}{2k_BT}
\right)^2
\frac{1}
{
\sinh^2
\left(
\frac{\hbar\omega}{2k_BT}
\right)
}
}
$$


# 5. High Temperature Limit

For:

$$
k_BT\gg\hbar\omega
$$

we have:

$$
x=
\frac{\hbar\omega}{2k_BT}
\rightarrow0
$$

Using:

$$
\sinh(x)\approx x
$$

we get:

$$
C_V=
k_B
\frac{x^2}{x^2}
$$

Therefore:

$$
\boxed{
C_V\rightarrow k_B
}
$$

At high temperatures the quantum harmonic oscillator behaves like a classical harmonic oscillator.

This agrees with the classical equipartition theorem:

$$
\boxed{
C_V=k_B
}
$$

# Maximum Entropy Distribution under Mean and Variance Constraints

The Shannon entropy for a continuous probability distribution \(p(x)\) is:

$$
S=-\int p(x)\ln p(x)\,dx
$$

We maximize the entropy subject to the following constraints.

## Normalization Constraint

$$
\int p(x)\,dx=1
$$

## Mean Constraint

$$
\int xp(x)\,dx=\mu
$$

## Variance Constraint

$$
\int (x-\mu)^2p(x)\,dx=\sigma^2
$$


# 1. Constructing the Lagrangian

Using Lagrange multipliers, the constrained entropy function is:

$$
\mathcal{L}
=
-\int p(x)\ln p(x)\,dx
-\lambda_0
\left(
\int p(x)\,dx-1
\right)
$$

$$
-\lambda_1
\left(
\int xp(x)\,dx-\mu
\right)
-\lambda_2
\left(
\int (x-\mu)^2p(x)\,dx-\sigma^2
\right)
$$


# 2. Maximizing the Entropy

For maximum entropy:

$$
\frac{\delta \mathcal{L}}{\delta p(x)}=0
$$

Differentiating:

$$
-\left(\ln p(x)+1\right)
-\lambda_0
-\lambda_1x
-\lambda_2(x-\mu)^2
=0
$$

Rearranging:

$$
\ln p(x)
=
-1-\lambda_0
-\lambda_1x
-\lambda_2(x-\mu)^2
$$

Taking exponential on both sides:

$$
p(x)
=
e^{-1-\lambda_0}
e^{-\lambda_1x}
e^{-\lambda_2(x-\mu)^2}
$$

Let:

$$
A=e^{-1-\lambda_0}
$$

Therefore:

$$
p(x)
=
A
e^{-\lambda_1x-\lambda_2(x-\mu)^2}
$$


# 3. Simplification

The linear term can be absorbed into the quadratic term by completing the square.

Therefore, the maximum entropy distribution has the form:

$$
p(x)=Ae^{-a(x-\mu)^2}
$$

where:

$$
a>0
$$


# 4. Applying the Normalization Constraint

Using:

$$
\int_{-\infty}^{\infty}p(x)dx=1
$$

Substituting:

$$
A
\int_{-\infty}^{\infty}
e^{-a(x-\mu)^2}dx=1
$$

Using the Gaussian integral:

$$
\int_{-\infty}^{\infty}e^{-ax^2}dx
=
\sqrt{\frac{\pi}{a}}
$$

Therefore:

$$
A
\sqrt{\frac{\pi}{a}}
=1
$$

Hence:

$$
A=\sqrt{\frac{a}{\pi}}
$$


# 5. Applying the Variance Constraint

The variance is given by:

$$
\sigma^2
=
\int_{-\infty}^{\infty}
(x-\mu)^2p(x)dx
$$

Substituting:

$$
\sigma^2
=
A
\int_{-\infty}^{\infty}
(x-\mu)^2
e^{-a(x-\mu)^2}dx
$$

For a Gaussian distribution:

$$
a=\frac{1}{2\sigma^2}
$$

Therefore:

$$
A=
\sqrt{\frac{1}{2\pi\sigma^2}}
$$


# 6. Final Maximum Entropy Distribution

Substituting \(A\) and \(a\):

$$
\boxed{
p(x)
=
\frac{1}{\sqrt{2\pi\sigma^2}}
\exp
\left(
-\frac{(x-\mu)^2}{2\sigma^2}
\right)
}
$$


# Conclusion

The probability distribution that maximizes the Shannon entropy while satisfying fixed mean and variance constraints is the Gaussian distribution:

$$
\boxed{
p(x)=\mathcal{N}(\mu,\sigma^2)
}
$$

Therefore, among all continuous probability distributions with a specified mean and variance, the Gaussian distribution has the maximum entropy.

# Multiclass Logistic Regression / Maximum Entropy Classifier for Email Classification

We consider a multiclass classification problem where an email is classified into one of \(K\) categories.

Let:

- \(x\) = feature vector extracted from the email
- \(y \in \{1,2,\dots,K\}\) = class label
- \(p(y|x)\) = probability of class \(y\) given the features

The objective is to find the probability distribution that maximizes entropy while satisfying feature constraints.

---

# 1. Maximum Entropy Principle

The conditional entropy is defined as:

$$
H(Y|X)
=
-\sum_x p(x)
\sum_y p(y|x)\ln p(y|x)
$$

For a given input \(x\), we maximize:

$$
\boxed{
H(Y|X)
=
-\sum_y p(y|x)\ln p(y|x)
}
$$

subject to feature constraints.

---

# 2. Feature Constraints

For each feature function \(f_i(x,y)\), the constraint is:

$$
\sum_x p(x)
\sum_y p(y|x)f_i(x,y)
=
\hat{f_i}
$$

where:

- \(f_i(x,y)\) represents a feature function
- \(\hat{f_i}\) represents the empirical expectation of the feature

The probability distribution must also satisfy the normalization constraint:

$$
\sum_y p(y|x)=1
$$

---

# 3. Constructing the Lagrangian

The Lagrangian function is:

$$
L=
-\sum_y p(y|x)\ln p(y|x)
$$

$$
-\sum_i\lambda_i
\left(
\sum_y p(y|x)f_i(x,y)-\hat{f_i}
\right)
$$

$$
-\lambda_0
\left(
\sum_y p(y|x)-1
\right)
$$


---

# 4. Maximizing the Lagrangian

Taking the derivative with respect to \(p(y|x)\):

$$
\frac{\partial L}{\partial p(y|x)}=0
$$

Therefore:

$$
-(\ln p(y|x)+1)
-\sum_i\lambda_i f_i(x,y)
-\lambda_0=0
$$

Rearranging:

$$
\ln p(y|x)
=
-1-\lambda_0
-\sum_i\lambda_i f_i(x,y)
$$

Taking exponential:

$$
p(y|x)
=
e^{-1-\lambda_0}
e^{-\sum_i\lambda_i f_i(x,y)}
$$

Let:

$$
Z(x)=e^{1+\lambda_0}
$$

Therefore:

$$
\boxed{
p(y|x)
=
\frac{
e^{-\sum_i\lambda_i f_i(x,y)}
}
{Z(x)}
}
$$

where the normalization function is:

$$
Z(x)
=
\sum_y
e^{-\sum_i\lambda_i f_i(x,y)}
$$

---

# 5. Softmax Form

The maximum entropy model can be written in the Softmax form:

$$
\boxed{
p(y=k|x)
=
\frac{
e^{w_k^Tx}
}
{
\sum_{j=1}^{K}e^{w_j^Tx}
}
}
$$

where:

- \(w_k\) is the weight vector for class \(k\)
- \(x\) is the input feature vector
- \(K\) is the number of classes

---

# 6. Email Classification Example

For email classification, the feature vector can be represented as:

$$
x=
[x_1,x_2,\dots,x_n]
$$

Possible features include:

- word frequency
- presence of spam keywords
- sender information
- email length

The probability of each class is:

$$
P(y=k|x)
=
\frac{
e^{w_k^Tx}
}
{
\sum_{j=1}^{K}e^{w_j^Tx}
}
$$

The predicted class is:

$$
\boxed{
\hat{y}
=
\arg\max_k P(y=k|x)
}
$$


---

# 7. Final Maximum Entropy Classifier

The final maximum entropy classifier for multiclass email classification is:

$$
\boxed{
P(y=k|x)
=
\frac{
\exp(w_k^Tx)
}
{
\sum_{j=1}^{K}
\exp(w_j^Tx)
}
}
$$

This model selects the probability distribution with maximum entropy while satisfying the observed feature constraints.

Therefore, the Maximum Entropy classifier is equivalent to **multiclass logistic regression using the Softmax function**.

In [1]:
# Import required libraries
import numpy as np
from scipy.optimize import minimize
import pandas as pd

# ----------------------------------------------------
# Multiclass Maximum Entropy / Softmax Model
# ----------------------------------------------------

# Feature vectors for emails
# Example features:
# x1 = spam keyword frequency
# x2 = email length
# x3 = suspicious word count

X = np.array([
    [2, 3, 1],
    [1, 5, 2],
    [4, 1, 3],
    [3, 2, 4]
])


# Email class labels
# 0 = Normal
# 1 = Spam
# 2 = Promotional

y = np.array([0, 1, 2, 2])


# Number of classes and features

num_classes = 3
num_features = X.shape[1]


# ----------------------------------------------------
# Softmax Function
# ----------------------------------------------------

def softmax(z):

    exp_values = np.exp(
        z - np.max(z, axis=1, keepdims=True)
    )

    return exp_values / np.sum(
        exp_values,
        axis=1,
        keepdims=True
    )


# ----------------------------------------------------
# Maximum Entropy Model
# ----------------------------------------------------

def model_probabilities(W, X):

    W = W.reshape(num_classes, num_features)

    scores = X @ W.T

    probabilities = softmax(scores)

    return probabilities



# ----------------------------------------------------
# Negative Log Likelihood Loss Function
# ----------------------------------------------------

def loss_function(W):

    probabilities = model_probabilities(W, X)

    loss = 0

    for i in range(len(X)):

        loss -= np.log(
            probabilities[i, y[i]]
        )

    return loss



# ----------------------------------------------------
# Train Model
# ----------------------------------------------------

initial_weights = np.zeros(
    num_classes * num_features
)


result = minimize(
    loss_function,
    initial_weights,
    method="BFGS"
)


# Optimized weights

W_opt = result.x.reshape(
    num_classes,
    num_features
)


print("Optimized Weight Matrix:")
print(W_opt)



# ----------------------------------------------------
# Predict Probabilities
# ----------------------------------------------------

probabilities = model_probabilities(
    result.x,
    X
)


# Display probabilities

df = pd.DataFrame(
    probabilities,
    columns=[
        "Normal",
        "Spam",
        "Promotional"
    ]
)

print("\nClass Probabilities:")
display(df)



# ----------------------------------------------------
# Predict Email Category
# ----------------------------------------------------

predicted_classes = np.argmax(
    probabilities,
    axis=1
)


print("\nPredicted Classes:")
print(predicted_classes)

Optimized Weight Matrix:
[[ 6.60894215  1.85440182 -8.80427252]
 [-7.24320431  2.96147966  2.75609945]
 [ 0.63426208 -4.81588752  6.04817113]]

Class Probabilities:


,Normal,Spam,Promotional
0,9.999973e-01,2.698835e-06,3.716913e-08
1,3.721432e-07,9.999996e-01,2.467510e-11
2,8.412961e-07,2.534667e-15,9.999992e-01
3,5.980179e-13,5.929260e-10,1.000000e+00



Predicted Classes:
[0 1 2 2]


# Asset Pricing and Portfolio Optimization Using Maximum Entropy

In this problem, the Maximum Entropy (MaxEnt) principle is used to estimate a continuous probability distribution of future asset returns.

The objective is to find the least biased probability distribution that satisfies known constraints such as expected return and risk.

---

# 1. Maximum Entropy Principle

The entropy of a continuous probability distribution \(p(r)\) is:

$$
S=-\int p(r)\ln p(r)\,dr
$$

where:

- \(r\) is the asset return.
- \(p(r)\) is the probability density function of returns.

The maximum entropy distribution is obtained by maximizing \(S\) subject to the available financial constraints.

---

# 2. Constraints on Asset Returns

## Normalization Constraint

The probability distribution must satisfy:

$$
\int p(r)\,dr=1
$$


## Expected Return Constraint

The expected return is:

$$
\int r\,p(r)\,dr=\mu
$$

where \(\mu\) is the expected return.


## Risk (Variance) Constraint

The variance of returns is:

$$
\int (r-\mu)^2p(r)\,dr=\sigma^2
$$

where \(\sigma^2\) represents the portfolio risk.

---

# 3. Constructing the Maximum Entropy Function

The constrained entropy function is:

$$
L=
-\int p(r)\ln p(r)\,dr
$$

$$
-\lambda_0
\left(
\int p(r)\,dr-1
\right)
$$

$$
-\lambda_1
\left(
\int r p(r)\,dr-\mu
\right)
$$

$$
-\lambda_2
\left(
\int (r-\mu)^2p(r)\,dr-\sigma^2
\right)
$$


---

# 4. Maximizing the Entropy

For maximum entropy:

$$
\frac{\delta L}{\delta p(r)}=0
$$

Differentiating:

$$
-(\ln p(r)+1)
-\lambda_0
-\lambda_1r
-\lambda_2(r-\mu)^2
=0
$$

Rearranging:

$$
\ln p(r)
=
-1-\lambda_0
-\lambda_1r
-\lambda_2(r-\mu)^2
$$

Taking the exponential:

$$
p(r)
=
A
e^{-\lambda_1r-\lambda_2(r-\mu)^2}
$$

where:

$$
A=e^{-1-\lambda_0}
$$

---

# 5. Maximum Entropy Return Distribution

By completing the square, the linear term can be incorporated into the quadratic term.

The distribution becomes:

$$
p(r)=Ae^{-a(r-\mu)^2}
$$

Using the normalization condition:

$$
\int_{-\infty}^{\infty}p(r)\,dr=1
$$

we obtain:

$$
A=\frac{1}{\sqrt{2\pi\sigma^2}}
$$

and:

$$
a=\frac{1}{2\sigma^2}
$$

Therefore, the maximum entropy distribution is:

$$
\boxed{
p(r)
=
\frac{1}{\sqrt{2\pi\sigma^2}}
\exp
\left(
-\frac{(r-\mu)^2}{2\sigma^2}
\right)
}
$$


---

# 6. Portfolio Optimization

For a portfolio containing multiple assets:

$$
R=w^Tr
$$

where:

- \(w\) is the vector of portfolio weights.
- \(r\) is the vector of asset returns.

The expected portfolio return is:

$$
E(R)=w^T\mu
$$

The portfolio variance is:

$$
\sigma_R^2=w^T\Sigma w
$$

where \(\Sigma\) is the covariance matrix.

---

# 7. Maximum Entropy Portfolio Model

The objective is:

$$
\max S
=
-\int p(R)\ln p(R)\,dR
$$

subject to:

$$
E(R)=w^T\mu
$$

and:

$$
Var(R)=w^T\Sigma w
$$

The resulting return distribution is:

$$
\boxed{
p(R)
=
\frac{1}{\sqrt{2\pi\sigma_R^2}}
\exp
\left(
-\frac{(R-\mu_R)^2}
{2\sigma_R^2}
\right)
}
$$


---

# Conclusion

The Maximum Entropy approach provides the least biased estimate of asset return distributions using only known information such as:

- expected return,
- variance,
- covariance between assets.

The resulting distribution is Gaussian:

$$
\boxed{
p(R)=\mathcal{N}(\mu_R,\sigma_R^2)
}
$$

This approach avoids unnecessary assumptions and provides an optimal probabilistic model for portfolio analysis.

In [2]:
# Import required libraries

import numpy as np
import plotly.graph_objects as go


# ----------------------------------------------------
# Maximum Entropy Parameters
# ----------------------------------------------------

lambda_1 = -0.1843

lambda_2 = 0.00114

lambda_3 = 0.4215


# Normalization constant

Z = 134.72



# ----------------------------------------------------
# Asset Price Range
# ----------------------------------------------------

S_T = np.linspace(
    0.1,
    200,
    1000
)



# ----------------------------------------------------
# Maximum Entropy Probability Density
# ----------------------------------------------------

pdf = (

    (1/Z)

    *

    (S_T ** (-lambda_3))

    *

    np.exp(
        -lambda_1*S_T
        -
        lambda_2*(S_T**2)
    )

)



# ----------------------------------------------------
# Plot Maximum Entropy Distribution
# ----------------------------------------------------

fig = go.Figure()


fig.add_trace(
    go.Scatter(
        x=S_T,
        y=pdf,
        mode="lines",
        name="Maximum Entropy PDF"
    )
)


fig.update_layout(

    title=
    "Maximum Entropy Asset Price Distribution",

    xaxis_title=
    "Future Asset Price",

    yaxis_title=
    "Probability Density",

    template=
    "plotly_white"

)


fig.show()



# ----------------------------------------------------
# Check Normalization
# ----------------------------------------------------

area = np.trapz(
    pdf,
    S_T
)


print(
    "Total Probability Area =",
    area
)

Total Probability Area = 107.64738675022564


/tmp/ipykernel_1233/3861700536.py:102: DeprecationWarning:

`trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.

